name: Check quality of source code.
run-name: ${{ github.actor }} is run check quality of source code. 🚀
on:
  push:
    branches:
      - "*"
      - "!main"
      - "!prod"
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run eslint
        run: npm run lint
