name: Build and deploy to github pages.
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build 🏗️
        run: npm i && npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zapder-artifact
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zapder/zapder.github.io repository
        uses: actions/checkout@v4
        with:
          repository: "zapder/zapder.github.io"
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: temp/zapder

      - name: Clear all file in "zapder/zapder.github.io"
        continue-on-error: true
        run: cd temp/zapder && git rm -rf .

      - name: Download zapder-artifact
        uses: actions/download-artifact@v3
        with:
          name: zapder-artifact
          path: temp/zapder

      - name: Commit and push to zapder/zapder.github.io repository 🚀
        run: cd temp/zapder && git add -A && (git commit -m "deploy new version" || true) && git push
        env:
          GIT_COMMITTER_NAME: Thiti Yamsung
          GIT_AUTHOR_NAME: Thiti Yamsung
          EMAIL: mr.thiti@icloud.com